config/routes.rb
RedditClone::Application.routes.draw do

  
  devise_for :users

  root 'posts#index'

  resources :posts, :comments do
    resources :comments
  end  

  get '/posts/:post_id/upvote', to: 'votes#upvote', as: 'upvote_post'
  get '/posts/:post_id/sidevote', to: 'votes#sidevote', as: 'sidevote_post'
  get '/posts/:post_id/downvote', to: 'votes#downvote', as: 'downvote_post'

  get '/comments/:comment_id/upvote', to: 'votes#upvote', as: 'upvote_comment'
  get '/comments/:comment_id/sidevote', to: 'votes#sidevote', as: 'sidevote_comment'
  get '/comments/:comment_id/downvote', to: 'votes#downvote', as: 'downvote_comment'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	has_many :comments, class_name: 'Comment', foreign_key: 'comment_id'
	belongs_to :comment, class_name: 'Comment'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :posts
    has_many :votes
    has_many :comments
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :find_post, only: [:new, :create, :update, :edit, :destroy]

  def index

  end

  def show

  end

  def new
  	@comment = Comment.new
    @comment_id = params[:comment_id]
  end

  def create
  	@comment = @post.comments.build(params[:comment].permit(:body))
  	@comment.user_id = current_user.id
    # if there is a comment then add that too
    if params[:comment_id]
      @comment.comment_id = params[:comment_id]
    end
  	@comment.save
  	redirect_to @post
  end

  def edit

  end

  def update
  	@comment.update_attributes!(params[:comment].permit(:body))
  	@comment.save
  	redirect_to @post
  end

  def destroy
  	@comment.destroy
  	redirect_to @post
  end

  private

  def find_comment
  	@comment = Comment.find(params[:id])
  end

  def find_post
  	@post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :find_post, only: [:show, :update, :edit, :destroy]
	before_action :find_vote, only: :show

	def index
		@posts = Post.order(:votes).reverse
		@votes = {}
		if current_user
			@posts.each do |post|
				@votes[post.id] = current_user.votes.find_by({item_id: post.id, item_type: 'post'})
			end
		end
	end

	def show

	end

	def create
		@post = Post.new(params[:post].permit(:title,:body))
		@post.user_id = current_user.id
		@post.save
		
		redirect_to root_url
	end

	def new
		@post = Post.new
	end

	def update
		@post.update_attributes!(params[:post].permit(:title,:body))
		redirect_to root_url
	end

	def edit

	end

	def destroy
		@post.destroy
		redirect_to root_path
	end


	private



	def find_post 
		@post = Post.find(params[:id])
	end

	def find_vote
		if current_user
			@vote = current_user.votes.find_by(item_id: @post.id, item_type: 'post')
		end
	end	

	def post_params
		params.require(:post).permit(:title,:body)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_action :find_post
	before_action :find_comment
	before_action :find_vote

	def upvote
		
		if @comment.nil?
			@item = @post
		else
			@item = @comment
		end

		if @vote.nil?
			@vote = Vote.new
			@vote.item_id = @item.id
			@vote.item_type = item_type(@item)
			@vote.user_id = current_user.id
		end

		if @vote.upvote.nil?
			@item.votes += 1
			@vote.upvote = true
		elsif @vote.upvote == false
			@item.votes += 2
			@vote.upvote = true
		end

		@item.save
		@vote.save

		if item_type(@item) == 'comment'
			redirect_to post_path(@post)
		else
			redirect_to root_path
		end
	end

	def downvote

		if @comment.nil?
			@item = @post
		else
			@item = @comment
		end

		if @vote == nil
			@vote = Vote.new
			@vote.item_id = @item.id
			@vote.item_type = item_type(@item)
			@vote.user_id = current_user.id
		end

		if @vote.upvote.nil?
			@item.votes -= 1
			@vote.upvote = false	
		elsif @vote.upvote == true
			@item.votes -= 2
			@vote.upvote = false			
		end

		@item.save
		@vote.save

		if item_type(@item) == 'comment'
			redirect_to post_path(@post)
		else
			redirect_to root_path
		end
	end

	def sidevote

		if @comment.nil?
			@item = @post
		else
			@item = @comment
		end
		
		if @vote.upvote
			@item.votes -= 1
		elsif @vote.upvote == false
			@item.votes += 1
		end
		@item.save
		@vote.destroy

		if item_type(@item) == 'comment'
			redirect_to post_path(@post)
		else
			redirect_to root_path
		end
	end

	private

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_comment
		unless params[:comment_id].nil?
			@comment = Comment.find(params[:comment_id])
		end
	end

	def find_vote
		if @comment.nil?
			@vote = current_user.votes.find_by(:item_id => @post.id, item_type: 'post')
		else
			@vote = current_user.votes.find_by(:item_id => @comment.id, item_type: 'comment')
		end
	end

	def item_type(item)
		if @comment.nil?
			return 'post'
		else
			return 'comment'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def item_comments(item)
		if item.is_a?Post
			item.comments.where(comment_id: nil)
		elsif item.is_a?Comment
			if item.comments
				item.comments
			else
				false
			end
		else
			raise 'error'
		end
	end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>

	<%= f.label :body %>:
	<%= f.text_field :body %><br>

	<%= hidden_field_tag(:comment_id, @comment_id) %>

	<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

<%= render 'form' %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<%= comment.votes %> | 
<%= link_to 'Upvote', { controller: :votes, action: :upvote, post_id: post.id, comment_id: comment.id, type: :comment } %><br>
<%= link_to 'Sidevote', { controller: :votes, action: :sidevote, post_id: post.id, comment_id: comment.id, type: :comment } %><br>
<%= link_to 'Downvote', { controller: :votes, action: :downvote, post_id: post.id, comment_id: comment.id, type: :comment } %><br>
<%= comment.body %><br>
Posted at <%= l comment.created_at, format: :short %><br>
By <%= comment.user.email %>

<% if current_user.id == comment.user.id %>
	<%= link_to 'Edit', edit_post_comment_path(@post,comment) %>
	<%= link_to 'Delete', post_comment_path(@post,comment), method: :delete %>
<% end %>
<%= link_to 'Reply', { controller: 'comments', action: :new, comment_id: comment.id, post_id: @post.id } %>


<% # Comments comments and comments comments comments etc. %>
<% if item_comments(comment) %>
	<% item_comments(comment).each do |comment| %>
		<p>
			<%= render 'comment', post: post, comment: comment %>
		</p>
	<% end %>
<% end %>	

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>:
	<%= f.text_field :title %><br>

	<%= f.label :body %>:
	<%= f.text_field :body %><br>

	<%= f.submit %>
<% end %>

app/views/posts/_votes.html.erb
<div class='votes'> <%= pluralize(post.votes, 'vote') %></div>
<div class='upvote <%= 'selected' if @vote and @vote.upvote  %>'>
	<%= link_to 'Upvote', upvote_post_path(post), { remote: true, onclick: "change_vote(#{post.id.to_s},'upvote')" } %>
</div>

<div class='sidevote <%= 'selected' if @vote.nil?  %>'>
	<%= link_to 'Sidevote', sidevote_post_path(post), { remote: true, onclick: "change_vote(#{post.id.to_s},'sidevote')" }  %>
</div>
<div class='downvote <%= 'selected' if @vote and @vote.upvote == false %>'>
	<%= link_to 'Downvote', downvote_post_path(post), { remote: true, onclick: "change_vote(#{post.id.to_s},'downvote')" }  %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts Index</h1>

<% if current_user %>
	Logged in as <%= current_user.email %>.
	<%= link_to 'Sign out', destroy_user_session_path, {method: :delete} %>
<% else %>
	<%= link_to 'Sign in', new_user_session_path %>
<% end %>
<p>This is where the posts go.</p>

<% @posts.each do |post| %>
	<% @vote = @votes[post.id] %>
	<div class='post' id='post-<%= post.id %>'>

		<%= render 'votes', post: post %>
		
		|
		
		<% if current_user and post.user_id == current_user.id %><b><% end %>
		<%= link_to post.title, post_path(post) %>
		<% if current_user and post.user_id == current_user.id %></b><% end %>
	</div>
<% end %>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
	<%= f.label :title %>:
	<%= f.text_field :title %><br>

	<%= f.label :body %>:
	<%= f.text_field :body %><br>

	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class='post' id='post-<%= @post.id %>'>

<%= render 'votes', post: @post %>

<h1 id='post-title'><%= @post.title %></h1>
<p>
	<%= @post.body %>
</p>
</div>
<div id='comments'>
<h2>Comments</h2>
<% item_comments(@post).each do |comment| %>
	<p>
		<%= render 'comment', post: @post, comment: comment %>
	</p>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Delete', post_path(@post), method: :delete %>

<%= link_to 'New Comment', new_post_comment_path(@post) %>
</div>